name: 'Idea CLI Inspector'
description: 'This action can be used to run idea-cli-inspector'
author: 'lionzxy'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-square'
  color: 'green'
